import module_journal
def test():
    pr1 = module_journal.Lesson("Высокоинтеллектуальные платформы", 144, "Мартин Кютц", "7-8")
    pr3 = module_journal.Lesson("Алгоритмические ЯП", 180, "Курушин", "9-10")
    pr2 = module_journal.Titul("Пермский национальный исследовательский политехнический университет", "Электортехнический факультет", "2019/2020", "АСУ2-19-1м")
    pr4 = module_journal.Students(1, "Фоминых", "Полина", "Юрьевна")
    pr5 = module_journal.Students(2, "Орлова", "Екатерина", "Дмитриевна")
    module_journal.Titul.__enter__(pr2)
    module_journal.Students.__enter__(pr4)
    module_journal.Students.__enter__(pr5)
    module_journal.Lesson.__enter__(pr1)
    module_journal.Lesson.__enter__(pr3)
    print("-------------------------")
    prch = module_journal.Journal("university", "faculty", "years", "group", "name_subject", "time", "teacher", "pages", "number", "surname", "name", "middle_name")
    print(module_journal.Journal.__str__(prch), "\n")
    print(module_journal.Journal.__repr__(prch))
    prch1 = module_journal.Journal('university','faculty','years','group','name_subject','time','teacher','pages','number','surname','name','middle_name')
    print(module_journal.Journal.__repr__(prch1))
if __name__ == '__main__':
    test()